### ISSUE TITLE
Timestamp is not round-trip equivalent with Display and parse()

### ISSUE THREAD

**Issue by chachi** [atolab/uhlc-rs#15]
The `+ 1` at the end of the `impl From<Duration>` breaks stringifying and then parsing the same number back out.

https://github.com/atolab/uhlc-rs/blob/68bf15965061951bb4d11db9c54acf9ba5235b00/src/ntp64.rs#L231

The following test fails:
```rust
    #[test]
    fn test_exact_parse() {
        use std::str::FromStr;
        let id1: ID = ID::try_from([0x01]).unwrap();
        let ts1 = Timestamp::new(NTP64(100), id1);
        assert_eq!(ts1, Timestamp::from_str(&ts1.to_string()).unwrap());
    }
```

**Comment by chachi** [comment]
Hmm on further investigation, this may be due to the nanosecond rounding more than the +1

**Comment by JEnoch** [comment]
Right, the root cause is the rounding.

The `Display` trait and thus the `ToString` trait convert the NTP64 to a RFC3339 representation to be more "human readable".
As the last 32 bits of a NTP64 is the fraction of 1 second, converting this fraction to any subdivision of the second requires to make a division by 2^32. This means that `1u64` as NTP64 represents approximately 0,232830644 nanoseconds.

Thus converting a NTP64 to string and then back to NTP64 will give back the same number in only for ~23,28% of the numbers.
e.g. this test succeeds:
```rust
    #[test]
    fn test_exact_parse() {
        use std::str::FromStr;
        let id1: ID = ID::try_from([0x01]).unwrap();
        let ts1 = Timestamp::new(NTP64(104), id1);
        assert_eq!(ts1, Timestamp::from_str(&ts1.to_string()).unwrap());
    }
```
